### PR TITLE
Add 2.5 second timeout for AMF test process

### PR DESCRIPTION
**Pull request by notr1ch**
### Description
Adds a 2.5 second timeout to the enc-amf-test on Windows, after which point the process self-terminates.

### Motivation and Context
Some users report the OBS UI failing to appear despite obs64.exe running. In one case, this was caused by the AMF test executable freezing, and OBS waiting forever on a pipe `ReadFile` call. Self-terminating the test executable seemed like an easier implementation than asynchronous pipe I/O and has the benefit of cleaning up the frozen process.

Yes, it is a bit hacky, but AMF is long overdue for a rewrite anyway.

Ref: https://github.com/obsproject/obs-studio/issues/6230

### How Has This Been Tested?
Ran enc-amf-test with hardcoded delays and verified it terminated and OBS reported a timeout.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
Any reason not to use "Fixes #6230"?

**Comment by notr1ch** [comment]
I wasn't sure that worked across repositories.

**Comment by RytoEX** [comment]
You can leave it for a submodule update commit if you prefer.

**Comment by vivi90** [comment]
pls merge

**Pull request merged**
