### PR TITLE
V2.6

### PR DESCRIPTION
**Pull request by Xaymar**
### Description
Adjusts the project for the 2.6 release.

### Motivation and Context
Releases a new version.

### How Has This Been Tested?
Tested with the following GPUs:
- [x] XFX RX 480
- [x] XFX Vega VII

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by Xaymar** [comment]
@jpark37 Waiting on the green light from you with your C++17 changes.

**Comment by Xaymar** [comment]
Tests delayed until HW arrives on Saturday.

**Comment by jpark37** [comment]
The only two things stopping the C++17 change at https://github.com/obsproject/obs-studio/pull/2081 are https://github.com/obsproject/obs-studio/pull/2095, ~~and a version of the obs-browser submodule being promoted with the register keyword removal~~ (Jim just updated the submodule 10 minutes ago).

**Comment by Xaymar** [comment]
Test suite failed on the Vega VII. Successful on the RX 480 though.

**Comment by Xaymar** [comment]
@jpark37 Can you test this on your AMD card? It now works flawlessly on my two RX 480s and my Vega VII. According to a helpful user (Clybius) it also now works on the PowerColor 5700 XT, which hard crashed before.

**Comment by Xaymar** [comment]
@jp9000 Gonna need your approval for removing the AMF submodule and replacing it with a smaller static version.

**Pull request merged**
