### PR TITLE
amf: Deprecate legacy AMD encoder

### PR DESCRIPTION
**Pull request by derrod**
### Description

Add deprecated flag to encoder.

### Motivation and Context

Encoder has been replaced.

### How Has This Been Tested?

Testing?

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by dodgepong** [comment]
Can we also add a "(deprecated)" or "(legacy)" label to the old encoder entry on the encoder list?

**Comment by RytoEX** [comment]
Superseded by https://github.com/obsproject/obs-amd-encoder/commit/5880f37307dbf36a4dc2dfc75ab13bbbfd055102 ?

**Comment by derrod** [comment]
Yes

**Comment by jp9000** [comment]
Sorry about that, didn't see this one (darn submodules)

**Comment by RytoEX** [comment]
No worries. The important thing is that we get the deprecation done.

**Pull request closed without merging**
