### PR TITLE
include: Load platform depended macros

### PR DESCRIPTION
**Pull request by SuslikV**
"snprintf" is macro in OBS Studio.

### CODE REVIEW

**Comment by Xaymar** [comment]
What is this supposed to fix?

By the way, snprintf is a function of standard C++11: http://www.cplusplus.com/reference/cstdio/snprintf/, https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l

**Comment by SuslikV** [comment]
Not a big deal (info at the Remark part of the Microsoft link), but I noticed it when tried to compile plugin together with the OBS Studio in VS 2013. Of course, the plugin itself incompatible with the VS 2013 as I understand.

**Comment by Xaymar** [comment]
Visual Studio 2013 is not supported and the support for it was originally kept to make the plugin build with obs-studio. The minimum Visual Studio version is 2015, the recommended version is 2017 or clang.

> Beginning with the UCRT in Visual Studio 2015 and Windows 10, snprintf is no longer identical to _snprintf. The snprintf function behavior is now C99 standard compliant.

See https://linux.die.net/man/3/snprintf, https://www.gnu.org/software/libc/manual/html_node/Formatted-Output-Functions.html

**Comment by SuslikV** [comment]
So, you want to keep it as is and ignore macro for OBS Studio?

**Comment by Xaymar** [comment]
I see very little reason to have it, but it doesn't seem to break any of the build types. Merged.

**Pull request merged**
